# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180613_1051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirmstring',
            table='confirm_string',
        ),
    ]
